### ISSUE TITLE
Spriggymon doesnt work in new editor [sprig v2]

### ISSUE THREAD

**Issue by the456gamer** [hackclub/sprig#857]
https://sprig-beta.hackclub.dev/gallery/spriggymon
This is the only game i've found that has issues

TypeError: "use strict" is not a function
    at eval (eval at $0 (editor.799a3782.js:34:100), <anonymous>:8:1)
    at $0 (editor.799a3782.js:34:133)
    at Object.u [as onClick] (editor.799a3782.js:229:2057)
    at Object.onClick [as clickfalse] (sprig-icon.02e5e07c.js:7:108)
    at HTMLButtonElement.B (preact.module.3821bb68.js:1:4195)
u @ editor.799a3782.js:229
onClick @ sprig-icon.02e5e07c.js:7
B @ preact.module.3821bb68.js:1

**Comment by kognise** [comment]
REALLY good catch, thank you! I accidentally removed the semicolon after the `"use strict"` we insert before games, and Spriggymon starts with an IIFE (so JS tries to call the string as a function)
